name: Test
on:
  - push
  - pull_request
jobs:
  docker:
    name: ${{ matrix.distribution }}
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - almalinux
          - alt-linux
          - arch-linux
          - debian
          - fedora
          - opensuse
          # - pld-linux
          - ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker-compose build ${{ matrix.distribution }}
      - name: Run
        run: |
          docker-compose run ${{ matrix.distribution }}

  native:
    name: ${{ matrix.ruby-version }} on ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - macos
          - ubuntu
          - windows
        ruby-version:
          - "3.1"
          - "3.0"
    runs-on: ${{ matrix.runs-on }}-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - run: bundle exec rake test
      - run: rake install
      - run: gem install glib2
        if: |
          matrix.runs-on != 'windows'
      # "gem install" installs native package on Windows.
      # So we need to use extconf.rb to test native-package-installer.
      - uses: actions/checkout@v2
        if: |
          matrix.runs-on == 'windows'
        with:
          repository: ruby-gnome/ruby-gnome
          path: ruby-gnome
      - name: Install glib2 from source
        if: |
          matrix.runs-on == 'windows'
        run: |
          gem install pkg-config
          cd ruby-gnome\glib2
          ridk exec ruby extconf.rb
          ridk exec make
          ridk exec ruby -Ilib -Iext/glib2 -e "require 'glib2'"
